version: '3.8'

services:
  app:
    build: ./docker
    ports:
      - "8081:80"
    volumes:
      # Mount source-code for development
      - ./:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=expense_tracker
      - MYSQL_USER=expense_tracker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - './db:/docker-entrypoint-initdb.d' #persist sql db when container stops
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
